# Generated by Django 4.1.7 on 2023-02-22 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssets',
            fields=[
                ('FixedAssetID', models.AutoField(primary_key=True, serialize=False)),
                ('FixedAssetName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FixedAssets',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Wallet',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AssetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fixedassets')),
                ('WalletID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wallet')),
            ],
            options={
                'db_table': 'Assets',
            },
        ),
    ]
