# Generated by Django 4.1.7 on 2023-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipassets',
            name='AssetStatus',
            field=models.BooleanField(default=True),
        ),
    ]
