# Generated by Django 4.1.7 on 2023-02-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sip',
            name='EnoughBalance',
            field=models.BooleanField(default=True),
        ),
    ]
